
# Project profile info
name: 'gg_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

default:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE') }}"
      threads: 10
      timeout_seconds: 300
      location: US
      priority: interactive

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  gg_project:
    +materialized: view
    # Applies to all files under models/example/
    example:
      +schema: example
    # Space for all the raw source data
    source:
      +schema: source
    # Space for staing and transformation models
    gg_model:
      staging:
        +database: gg_model
        +schema: staging
      modeled:
        +database: gg_model
        +schema: modeled
        finance:
          +database: gg_model
          +schema: modeled.finance
        sales:
          +database: gg_model
          +schema: modeled.sales
        company_kpi:
          +database: gg_model
          +schema: modeled.company_kpi
      
